### ISSUE TITLE
I couldnt get it working on latest xcode version

### ISSUE THREAD

**Issue by Boaztheostrich** [hoiberg/BluetoothSerialPro#1]
just a heads up for anyone finding this

**Comment by hoiberg** [comment]
Yes it will require some work to get it to compile. Someone else has already done so and put it up on the App Store again. Not sure if all features are working though.

Link: https://apps.apple.com/nl/app/bleserial-hm-10/id1602239700?l=en

He also re-uploaded the lite version: https://apps.apple.com/nl/app/ble-serial-tiny/id1607862132

As far as I know he has not published the source code though.

**Comment by Boaztheostrich** [comment]
I figured out how to get it to compile for anyone who might stumble upon this, all you need to do is just add privacy always usage description under targets > info > custom ios target properties.

I plan to keep working on this to try and get it to work on my project thanks for releasing the code you've saved me a ton of work.

![Screen Shot 2022-07-18 at 10 24 19 AM](https://user-images.githubusercontent.com/81034456/179545992-b6ac1787-299c-4f64-befb-d39b73af0e96.jpg)
